### ISSUE TITLE
Add mods.toml parser

### ISSUE THREAD

**Issue by Minecrell** [SpongePowered/plugin-meta#11]
Adding a `mods.toml` parser/emitter inside `plugin-meta` should be the easiest way to move forward in 1.13 without requiring too many changes in SpongeAPI/SpongeVanilla/SpongeGradle/Ore.

See https://github.com/cpw/MinecraftForge/blob/fmloverhaul/mods.toml

**Comment by Zidane** [comment]
Now that we mostly have the new metadata format in place, this can be done.

**Comment by Zidane** [comment]
No longer a focus of this library to do. Instead, Forge can be asked to move their parser out to a lib.
