### ISSUE TITLE
Establish Plugin "ID" rules

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/plugin-meta#14]
We need to establish if the "ID" rules used for the mcmod-info submodule would be applicable to all modules.

**Comment by kashike** [comment]
If you are referring to https://github.com/SpongePowered/plugin-meta/blob/master/mcmod-info/src/main/java/org/spongepowered/plugin/meta/PluginMetadata.java#L60, then it should. The same rules are used by Forge and Velocity, so it is a common rule.

**Comment by Zidane** [comment]
@kashike Sounds good to me, we'll continue to use that.
