### ISSUE TITLE
Print warning if version string is not comparable by maven's ComparableVersion

### ISSUE THREAD

**Issue by windy1** [SpongePowered/plugin-meta#3]
Additionally, it would by nice to add a plugin comparator to this library. This supersedes the release channel issue since maven version's can just have the channel appended to it.

**Comment by liach** [comment]
Or to check whether it matches semver?

**Comment by windy1** [comment]
I think the maven constraint would be most useful here tbh. Eventually, it would be nice if Ore projects were automatically deployed to a maven repo.

**Comment by Minecrell** [comment]
When is a version not parsable by `ComparableVersion`? Doesn't look like it puts any requirement on the version.

**Comment by Minecrell** [comment]
@windy1
Is this still an issue? Generally, every version should be comparable by `ComparableVersion`. The `getFirstString` method will return the release channel if it is present.
